package wasmcloud:template@0.1.0;

world http-api {
  import wasi:http/types@0.3.0;
  import wasi:clocks/types@0.3.0;
  import wasmcloud:messaging/types@0.3.0;
  import wasmcloud:messaging/consumer@0.3.0;
  export wasi:http/handler@0.3.0;
}

world task {
  import wasmcloud:messaging/types@0.3.0;
  import wasmcloud:messaging/consumer@0.3.0;
  import wasi:config/store@0.2.0-rc.1;
  export wasmcloud:messaging/handler@0.3.0;
}
